#!/usr/bin/env python
"""PR #647 — byte-comparability guard for the scheme-delta comparison.

The ALT GPTQ body is served under THIS venv (vLLM 0.22.0 + compressed-tensors 0.17.1,
the version llm-compressor 0.12.0 pulled in). The QAT comparison cells (#637 banked
``ar_gpqa.jsonl`` / ``ar_aime.jsonl``) were generated by the SAME server venv
(``gen_paired_greedy.py`` SERVER_PY == this one), but possibly before the CT 0.17.1
bump. compressed-tensors only *parses/packs* the checkpoint; vLLM's Marlin kernel does
the compute — so inference logits should be version-independent. This script PROVES it:
re-serve the live QAT body now and check the first N banked GPQA + AIME completions
reproduce byte-for-byte (same completion_token_ids). If they do, the QAT cells are a
clean, version-matched comparison point for the ALT cells. If not, the comparison would
be confounded and the QAT cells must be regenerated under this venv.

Reuses eval_alt_ar's request path + serve env verbatim (same M=1 AR, drafter OFF,
BI=1) so the only thing under test is the served checkpoint + toolkit version.

ANALYSIS-ONLY. Local A10G. NO HF Job, NO submission.

Usage:
  verify_qat_repro.py --body /workspace/gemma_build/int4_g128_lmhead --n 5
"""
from __future__ import annotations

import argparse
import json
import sys
import threading
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import eval_alt_ar as E  # noqa: E402

QAT_BANKED = E.QAT_BANKED
RES = E.RES

# GPQA banked cell used mml 6144; AIME used mml 8192 (see #637 gen_meta). We replay each
# item at the SAME eff cap it was banked with (its recorded max_tokens_eff), so the only
# variable is the toolkit version, not the generation budget.
MML_BY_KIND = {"gpqa": 6144, "aime": 8192}


def _replay(kind: str, body: str, n: int) -> dict:
    items = E.load_items_from_banked(kind)
    banked = {str(json.loads(l)["id"]): json.loads(l)
              for l in (QAT_BANKED / f"ar_{kind}.jsonl").read_text().splitlines() if l.strip()}
    items = items[:n]
    E.MAX_MODEL_LEN = MML_BY_KIND[kind]
    extra_env = E._spec_env(body)
    log_path = RES / f"_verify_qat_{kind}.log"
    print(f"[verify] {kind}: serving QAT body {body} mml={E.MAX_MODEL_LEN} n={len(items)}", flush=True)
    results = []
    with E.harness.LocalServer(
        E.SUBMISSION, server_python=E.SERVER_PY, port=E.PORT, log_path=log_path,
        extra_env=extra_env, startup_timeout_s=1800,
    ) as srv:
        for it in items:
            b = banked[it["id"]]
            eff = b["max_tokens_eff"]
            resp = E.request_greedy(srv.base_url, srv.served_model_name, it["prompt_token_ids"], eff)
            choice = E._DO.choice_from_response(resp)
            comp_ids, _src, _k = E._DO.extract_generated_token_ids(resp, choice, it["prompt_token_ids"])
            match = comp_ids == b["completion_token_ids"]
            results.append({
                "id": it["id"], "kind": kind, "eff": eff,
                "n_now": len(comp_ids), "n_banked": len(b["completion_token_ids"]),
                "byte_exact": match,
                "first_div": next((i for i, (x, y) in enumerate(
                    zip(comp_ids, b["completion_token_ids"])) if x != y), None),
            })
            print(f"[verify]   {it['id']}: now={len(comp_ids)}tok banked={len(b['completion_token_ids'])}tok "
                  f"-> {'BYTE-EXACT' if match else 'DIVERGENT @'+str(results[-1]['first_div'])}", flush=True)
    return {"kind": kind, "n": len(results), "n_exact": sum(r["byte_exact"] for r in results),
            "items": results}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--body", default="/workspace/gemma_build/int4_g128_lmhead")
    ap.add_argument("--evals", default="gpqa,aime")
    ap.add_argument("--n", type=int, default=5)
    args = ap.parse_args()
    RES.mkdir(parents=True, exist_ok=True)
    for note in E.paths.prepare_local_gpu_env():
        print(f"[gpu] {note}", flush=True)
    out = {"body": args.body, "analysis_only": True, "official_tps": 0, "by_kind": {}}
    for kind in [e.strip() for e in args.evals.split(",") if e.strip()]:
        out["by_kind"][kind] = _replay(kind, args.body, args.n)
    out["all_byte_exact"] = all(v["n_exact"] == v["n"] for v in out["by_kind"].values())
    (RES / "qat_repro.json").write_text(json.dumps(out, indent=2))
    print(f"\n[verify] === RESULT === all_byte_exact={out['all_byte_exact']}", flush=True)
    for k, v in out["by_kind"].items():
        print(f"[verify]   {k}: {v['n_exact']}/{v['n']} byte-exact", flush=True)
    print(f"[verify] wrote {RES/'qat_repro.json'}", flush=True)
    return 0 if out["all_byte_exact"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
