"""PR #651 validation: are the on-AR-head WIDE breaks (recompute_margin>1e-6) genuine
acceptor flips, or a prefill-vs-decode int4-Marlin M-dependence artifact?

rescue_capture.py rebuilds the context KV with a single max_tokens=1 request whose PREFILL
processes the whole prefix at once (GEMM M=len(prefix)). ar_ref_bi1 was generated by M=1
DECODE steps (one token at a time). The int4 Marlin GEMM is the lone M-dependent reduction
(#122), so at a near-tie the PREFILL-path argmax can differ from the DECODE-path argmax by
one int4 quantum (~0.125 nat) -- which is exactly what the 20 K=5 head 'wide' breaks look
like (verify_margin=0.0, recompute_margin=0.125/0.25, s_pos==a_pos).

This script isolates the cause. For every prompt that has >=1 wide on-AR-head break we
regenerate the stream the SAME way ar_ref was made -- prompt=ptoks, DECODE max_tokens to
reach the deepest break pos, temperature 0 -- on the same reference server, and check:

  (A) faithfulness anchor: does the decode-path stream reproduce ar_ref_bi1 byte-exact up to
      each break pos? (it must, if the ref engine is deterministic and decode==AR)
  (B) at each break pos: decode-path argmax == a_pos (the AR token) -> the break only exists
      on the prefill path == ARTIFACT; or == r_pos (the prefill recompute token) -> the flip
      is real and decode agrees with the prefill recompute (ar_ref would be the outlier).

analysis_only. Reuses rescue_capture's REF/AR_REF/post/loaders.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import rescue_capture as rc  # noqa: E402


def main() -> int:
    k = int(sys.argv[1]) if len(sys.argv) > 1 else 5
    cap = HERE / f"rescue_k{k}.jsonl"
    rows = [json.loads(l) for l in cap.read_text().splitlines() if l.strip()]
    wide = [r for r in rows
            if r["is_fire"] and r["pre_div"] and not r["rescue"]
            and r["recompute_margin"] is not None and r["recompute_margin"] > 1e-6]
    # group break positions by prompt
    by_pid: dict[str, list[dict]] = {}
    for r in wide:
        by_pid.setdefault(r["id"], []).append(r)
    print(f"[validate K={k}] {len(wide)} wide on-AR-head breaks across {len(by_pid)} prompts")

    prompts = rc.load_jsonl_by_id(rc.REF[k], ("prompt_token_ids",))
    ar = rc.load_jsonl_by_id(rc.AR_REF, ("completion_token_ids",))

    n_decode_eq_a = n_decode_eq_r = n_decode_other = 0
    n_ar_match_head = n_ar_mismatch_head = 0
    detail = []
    for pid, brks in sorted(by_pid.items()):
        ptoks = prompts[pid]["prompt_token_ids"]
        ar_ids = ar[pid]["completion_token_ids"]
        max_pos = max(b["pos"] for b in brks)
        # DECODE path: regenerate exactly like ar_ref (prompt only, greedy decode)
        payload = {
            "model": rc.MODEL, "prompt": ptoks,
            "max_tokens": max_pos + 1, "temperature": 0.0, "stream": False,
            "add_special_tokens": False, "ignore_eos": True,
            "return_token_ids": True, "logprobs": 20,
        }
        resp = rc.post(payload)
        choice = resp["choices"][0]
        dec = None
        for v in (choice.get("token_ids"), choice.get("output_token_ids"),
                  choice.get("completion_token_ids")):
            if isinstance(v, list) and v and isinstance(v[0], int):
                dec = v
                break
        if dec is None:
            raise ValueError(f"no token_ids for {pid}: keys={list(choice.keys())}")
        # (A) faithfulness: decode stream vs ar_ref up to max_pos
        cmp_n = min(max_pos + 1, len(ar_ids), len(dec))
        head_match = all(dec[i] == ar_ids[i] for i in range(cmp_n))
        n_ar_match_head += int(head_match)
        n_ar_mismatch_head += int(not head_match)
        first_mismatch = next((i for i in range(cmp_n) if dec[i] != ar_ids[i]), None)
        # (B) per break pos
        for b in brks:
            pos = b["pos"]
            dtok = dec[pos] if pos < len(dec) else None
            verdict = ("decode==a(AR)" if dtok == b["a_pos"]
                       else "decode==r(prefill)" if dtok == b["r_pos"]
                       else f"decode==other({dtok})")
            if dtok == b["a_pos"]:
                n_decode_eq_a += 1
            elif dtok == b["r_pos"]:
                n_decode_eq_r += 1
            else:
                n_decode_other += 1
            detail.append({
                "id": pid, "pos": pos, "a_pos": b["a_pos"], "r_pos_prefill": b["r_pos"],
                "decode_tok": dtok, "verdict": verdict,
                "recompute_margin_prefill": b["recompute_margin"],
                "verify_margin": b["verify_margin"],
                "decode_stream_eq_ar_ref_head": head_match,
                "ar_first_mismatch": first_mismatch,
            })
        print(f"  {pid}: decode_head==ar_ref={head_match} "
              f"(first_mismatch={first_mismatch}) breaks={len(brks)}")

    print(f"\n[A] faithfulness: decode-stream reproduces ar_ref on head for "
          f"{n_ar_match_head}/{len(by_pid)} prompts "
          f"({n_ar_mismatch_head} mismatched)")
    print(f"[B] wide-break resolution on the DECODE path:")
    print(f"     decode == a_pos (AR)        : {n_decode_eq_a}   <- prefill-path ARTIFACT (rescued on decode)")
    print(f"     decode == r_pos (prefill)   : {n_decode_eq_r}   <- genuine flip (decode agrees w/ prefill)")
    print(f"     decode == other             : {n_decode_other}")
    out = HERE / f"validate_decode_path_k{k}.json"
    out.write_text(json.dumps({
        "k": k, "n_wide_head_breaks": len(wide), "n_prompts": len(by_pid),
        "decode_eq_a_artifact": n_decode_eq_a, "decode_eq_r_genuine": n_decode_eq_r,
        "decode_other": n_decode_other,
        "decode_head_eq_ar_ref_prompts": n_ar_match_head,
        "decode_head_ne_ar_ref_prompts": n_ar_mismatch_head,
        "detail": detail,
    }, indent=2))
    print(f"[out] {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
